kc_sync
ottuco/keycloak-auth-utils pull request #10
Opened 2024-12-30 14:13 UTC by yamen-ottu

keycloak syncing and event handling through both consumer and apiview

2025-01-15 08:44 UTC, jab3z requested changes
make sure you apply the exception comments to all try/except blocks

2025-01-15 08:44 UTC, jab3z commented on src/keycloak_utils/consumer/rest_framework/core.py
> +import socket
import order not consistent, either use isort or handle manually. consider this comment for all imports across all files

2025-01-15 08:44 UTC, jab3z commented on src/keycloak_utils/consumer/rest_framework/core.py
> +logging.basicConfig(level=logging.INFO)
shouldn't this inherit the logging config of the django project where the package is installed?

2025-01-15 08:44 UTC, jab3z commented on src/keycloak_utils/consumer/rest_framework/core.py
> +            logger.info(f"the data is {event_data}")
any purpose why the logger is inside the try/except block?

2025-01-15 08:44 UTC, jab3z commented on src/keycloak_utils/consumer/rest_framework/core.py
> +        try:
huge try and except block, this is a super bad practice, when you are unsure of something can go wrong, you wrap everything in a try/exc block. thats not the way. every potential exception of your code must be handled individually

2025-01-15 08:44 UTC, jab3z commented on src/keycloak_utils/consumer/rest_framework/core.py
> +        except Exception as e:
ditch this, old topic to toooo broad exceptions, as i said in the early comment, deal with every exception separately and make sure it's specicific. good reading https://peps.python.org/pep-0760/

2025-01-15 08:44 UTC, jab3z commented on src/keycloak_utils/consumer/rest_framework/core.py
> +        self.should_stop = threading.Event()
threading library is not async safe. this code will not work with django/fastapi async, i mean it will work, but can have nasty side effects

2025-01-15 08:44 UTC, jab3z commented on src/keycloak_utils/consumer/rest_framework/core.py
> +        logger.info("Stopped consuming messages")
every logger should have a solid identifier, right? how else you can identify something specific in a sea of identical messages of `Stopped consuming messages`? Consider applying this for all logged messages

2025-01-15 08:44 UTC, jab3z commented on src/keycloak_utils/consumer/rest_framework/core.py
> +        except Exception as e:
same comment for Exceptions, we need to know which exceptions can our code trigger and handle them accordingly.

2025-01-15 08:44 UTC, jab3z commented on src/keycloak_utils/consumer/rest_framework/core.py
> +        except Exception as e:
Just saw down the line you are using KeyboardIntrerupt. you know that `Exception` is also suppressing that one also, will have no effect?

2025-01-15 08:57 UTC, yamen-ottu commented on src/keycloak_utils/consumer/rest_framework/core.py
> +            logger.info(f"the data is {event_data}")
debug step should be removed

2025-01-15 09:01 UTC, yamen-ottu commented on src/keycloak_utils/consumer/rest_framework/core.py
> +logging.basicConfig(level=logging.INFO)
this code was residing inside payout, forgot to remove it with core migration

2025-01-15 09:44 UTC, yamen-ottu commented on src/keycloak_utils/consumer/rest_framework/core.py
> +        logger.info("Stopped consuming messages")
will add in future commit to all

2025-01-30 05:53 UTC, yspanchal approved these changes

2025-02-03 07:42 UTC, merged